#!/bin/bash


#------------------------------------------------------------------------------#
# Rendered tmux status bar weather report.                                     #
# Checks report age to determine if a new data needs to be retrieved.          #
#------------------------------------------------------------------------------#

DEGREES=$'\xc2\xb0'

declare -A units=(
    # obs
    ["apparent_temp"]="${DEGREES}C"
    ["delta_t"]="${DEGREES}C"
    ["gust_kmh"]="km/h"
    ["wind_gust_spd"]="kn"
    ["air_temperature"]="${DEGREES}C"
    ["dew_point"]="${DEGREES}C"
    ["pres"]="hPa"
    ["msl_pres"]="hPa"
    ["qnh_pres"]="hPa"
    ["rain_hour"]="mm"
    ["rain_ten"]="mm"
    ["rel-humidity"]="% RH"
    ["wind_dir_deg"]="${DEGREES}"
    ["wind_spd_kmh"]="km/h"
    ["wind_spd"]="kn"
    # fcast
    ["air_temperature_minimum"]="${DEGREES}C"
    ["air_temperature_maximum"]="${DEGREES}C")


resolve_vars() {
    local -n vars=$1
    local -n data=$2
    declare -a out=()
    local __orientation=$(echo ${ORIENTATION} | tr '[:lower:]' '[:upper:]')
    local fmt=""
    local sep=""
    local seg=0
    local vars_len=${#vars[@]}

    for x in "${!vars[@]}"; do
        readarray -td'|' opts < <(printf '%s' "${vars[$x]}")
        local seg_style=""
        
        if [ $3 -eq 0 ]; then
            if [ $seg -eq 0 ]; then
                    __sym=$__orientation"_BOLD"
                    sep=" $SEG_ARROW_BOLD0${!__sym} " 
            elif [ $seg -eq $(expr $vars_len - 1) ]; then
                if [ $4 -eq 1 ]; then
                    __sym=$__orientation"_BOLD"
                    sep=" $SEG_ARROW_BOLD1${!__sym}"
                else
                    __sym=$__orientation"_BOLD"
                    sep="$SEG_ARROW_BOLD2${!__sym}"
                fi
            elif [ $seg -eq 1 ]; then
                __seg="SEG_STYLE$seg"
                seg_style=${!__seg}
                __sym=$__orientation"_THIN"
                sep=" $SEG_ARROW_THIN0${!__sym} "
            elif [ $seg -eq 2 ]; then
                __sym=$__orientation"_THIN"
                sep=" $SEG_ARROW_THIN0${!__sym} "
            fi
            ((seg++))
        else
            seg_style=" $LABEL_STYLE "
            __sym=$__orientation"_BOLD"
            sep=" $LABEL_ARROW_BOLD${!__sym}$SEG_STYLE0 "
        fi

        for y in "${!opts[@]}"; do
            declare -a _out=()
            local _fmt=""
            local fnd=0 #true
            local v0=$(echo "${opts[$y]}" | cut -d ";" -f 1)
            local v1=$(echo "${opts[$y]}" | cut -d ";" -f 2)
            readarray -td% fmts < <(printf '%s' "$v0")
            readarray -td, params < <(printf '%s' "$v1")
            local fmt_len=${#fmts[@]}

            if [ $fmt_len -gt 2 ]; then
                local fmt1_0=$(echo "$v0" | cut -d "%" -f 1)
                local fmt1="$fmt1_0%${fmts[1]}"
                local prm="${params[0]}"
                _fmt="${_fmt}${fmt1}"
                case $prm in
                    "units"_*) 
                        _out+=("${units[${prm#units_}]}") 
                        ;;
                    *) 
                        if [[ ! -z ${data[$prm]} ]]; then 
                            _out+=("${data[$prm]}")
                        else 
                            fnd=1
                        fi 
                        ;; 
                esac
                
                for f in $(seq 2 $(expr $fmt_len - 1)); do
                    _fmt="${_fmt}%${fmts[$f]}"             
                    local idx=$(expr $f - 1)
                    local prm=${params[$idx]}
                    
                    case $prm in
                        "units"_*) 
                            _out+=("${units[${prm#units_}]}") 
                            ;;
                        *) 
                            if [[ ! -z ${data[$prm]} ]]; then 
                                _out+=("${data[$prm]}")
                            else 
                                fnd=1
                            fi
                            ;;
                    esac
                    
                done
            else
                _fmt="${_fmt}$v0"
                local prm="$v1"
                case $prm in
                    "units"_*) 
                        _out+=("${units[${prm#units_}]}") 
                        ;;
                    *) 
                        if [[ ! -z ${data[$prm]} ]]; then 
                            _out+=("${data[$prm]}")
                        else 
                            fnd=1
                        fi 
                        ;; 
                esac
            fi
            
            # if we found everything (i.e. not found nothing)...
            if [ $fnd -eq 0 ]; then
                fmt="${fmt}${_fmt}"
                out+=( "${seg_style}${_out[@]}$sep" )
                break
            fi
        done
        
    done
    printf "${fmt}" "${out[@]}"
}


# Args: path_to_conf_file
parse_report() {
    local obs_rot=5
    local fcast_rot=1

    if [ -f "${OUTFILE}" ]; then
        # File exists
        local obs_rot=$(sed -n '3p' "$OUTFILE")
        is_int $obs_rot
        if [ $? -eq 0 ]; then
            local expiry=$(sed -n '1p' "$OUTFILE")
            local n_lines=$(sed -n '2p' "$OUTFILE")
            local fcast_rot=$(sed -n '4p' "$OUTFILE")
            local cur=$(expr ${obs_rot} + ${fcast_rot})
            if [ $(($cur)) -lt $(($n_lines)) ]; then
                load_dict obs <<< "$(sed -n "${obs_rot}p" "$OUTFILE")"
                if [ $((${fcast_rot})) -lt $((obs["n_fcast"])) ]; then
                    replace_line 4 "$(expr ${fcast_rot} + 1)" "$OUTFILE"
                else
                    replace_line 3 "$(expr $(($cur)) + 1)" "$OUTFILE"
                    replace_line 4 "1" "$OUTFILE"
                fi
            else
                replace_line 3 "5" "$OUTFILE"
                replace_line 4 "1" "$OUTFILE"
            fi
        fi

        local _obs="$(sed -n "${obs_rot}p" "$OUTFILE")"
        local _fcast="$(sed -n "$(expr ${obs_rot} + ${fcast_rot})p" "$OUTFILE")"
        


        
        if [[ $LEFTMOST = "obs" ]]; then 
            if [[ $ORIENTATION = "right" ]]; then o_is_last=1 f_is_last=0; fi
            if [[ $ORIENTATION = "left" ]]; then o_is_last=0 f_is_last=1; fi
        else
            if [[ $ORIENTATION = "right" ]]; then o_is_last=0 f_is_last=1; fi
            if [[ $ORIENTATION = "left" ]]; then o_is_last=1 f_is_last=0; fi
        fi

        


        load_dict orep <<< "$_obs"
        o_label=$(resolve_vars OBS_LABEL orep 1 1)
        o_data=$(resolve_vars OBS_VARS orep 0 $o_is_last)

        load_dict frep <<< "$_fcast"
        f_label=$(resolve_vars FCAST_LABEL frep 1 1)
        f_data=$(resolve_vars FCAST_VARS frep 0 $f_is_last)
        
        if [[ $ORIENTATION = "right" ]]; then
            fcast="$f_label$f_data"
            obs="$o_label$o_data"
        else
            fcast="$f_data$f_label"
            obs="$o_data$o_label"
        fi

        if [[ $LEFTMOST = "obs" ]]; then
            echo "#[align=$ALIGN]$obs$fcast"
        else
            echo "#[align=$ALIGN]$fcast$obs"
        fi        

        is_less_than $EPOCHSECONDS $expiry
        if [ $? -eq 0 ]; then
            # File is current, exit
            exit 0
        fi
    
    fi
    # File does not exist or is not current, call generator...
    # Check for running reports generator...
    
    #FIXME: dispatch fcast and obs labels with "updating..." in place of data
    pids=$(pidof -x "$TMUX_WEATHER_AU_SCRIPTS_DIR/weather-au-update.sh")
    err=$?
    if [ $(($err)) -eq 1 ]; then
        # Reports generator not running, fetch new data and generate reports...
        local cmd="$TMUX_WEATHER_AU_SCRIPTS_DIR/weather-au-update.sh $obs_rot $fcast_rot ${TMUX_WEATHER_AU_SRC_DIR} ${TMUX_WEATHER_AU_CONF_FILE}"
        $cmd & disown;
    # else Files are currently being generated, nothing to do, return.
    fi
}
